Change UI's
DefiLlama/chainlist pull request #445
Opened 2023-04-11 14:57 UTC by armbull

Some ui changes

- Added ability to copy RPC link to clipboard after clicking on the link text
- Added an effect of adding icon to the clipboard when hovering over a cell with a link
- Added effect of highlighting a cell with color when pointing with cursor
- Added animation of adding a link to the clipboard
- Fixed bug when switching to dark mode, scrolling remained always white in chrome. Now when you change the theme, scrolling is always in the theme color
- Added full screen mode, side menu folds into side menu. Looks much more convenient, especially for laptops.
- Tables on mobile resolution became more organic.
- Small bugs on mobile resolution.
- Added remembering the position of the side menu or full screen mode in localStorage.

Take the best, leave the rest.

2023-04-16 01:41 UTC, mintdart commented
hey can you resolve merge conflicts and revert changes in yarn.lock file?

2023-04-16 20:06 UTC, mintdart commented
i don't see `jsx` and `styled-jsx` packages used anywhere, can you revert changes in `package.json`, `yarn.lock` and remove `package-lock.json` ?

2023-04-18 05:52 UTC, armbull commented
Ok, it is not problem. I removed jsx and jsx-styled and decide to check with editing new ExtraRpcs.js and after `npm run dev` it shows `error - SerializableError: Error serializing `.chains[0].rpc[22].trackingDetails` returned from `getStaticProps` in "/"` so where I must add new line of code to solve this issue.

2023-04-20 11:37 UTC, Barry22588 approved these changes

2023-04-26 02:29 UTC, mintdart commented
can you revert changes in extraRpcs.js and keep this PR relevant to only UI changes ? , please revert changes in `extraRpcs.js` , `yarn.lock`, `package.json` and remove package-lock.json

2023-04-26 10:31 UTC, armbull commented
> can you revert changes in extraRpcs.js and keep this PR relevant to only UI changes ? , please revert changes in `extraRpcs.js` , `yarn.lock`, `package.json` and remove package-lock.json

I saw that you added new cell for ad in html. Hope it would be solve without my participate

2023-04-27 02:20 UTC, mintdart requested changes
please revert changes in `constants/chainIds.json` , `constants/extraRpcs.js` , rebase your branch with `main` and resolve merge conflicts, thanks 🙏

2024-06-05 10:33 UTC, Dioliode approved these changes
DioX

2024-10-03 07:58 UTC, OKEAMAH approved these changes

2024-12-17 05:08 UTC, SirJosh1987 approved these changes

2024-12-22 23:41 UTC, Setland34 approved these changes

2025-01-16 03:13 UTC, Setland34 approved these changes
Approved

2025-01-16 12:48 UTC, closed without merging